name: Check Back Button

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
  pull_request:
    paths:
      - "**/*.md"

jobs:
  check-markdown:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3
      # Run the check script
      - name: Verify Markdown Files
        run: |
          echo "Checking markdown files..."
          # Find all .md files excluding .github/ directory
          find . -name "*.md" \
            ! -path "./README.md" \
            ! -path "./.github/*" | while read file; do
              # Determine the relative path depth
              directory=$(dirname "$file")
              # Count the number of parent directories to calculate the correct number of `../`
              depth=$(echo "$directory" | tr -cd '/' | wc -c)
              
              if [[ "$depth" -eq 0 ]]; then
                # File is in root directory
                expected_line="⬅️ [Back to Main Menu](./README.md#contents)"
              else
                # File is in a subdirectory or deeper
                expected_line="⬅️ [Back to Main Menu]($(printf '../%.0s' $(seq 1 $depth))README.md#contents)"
              fi

              # Debugging: Print calculated values
              echo "Checking file: $file"
              echo "Directory: $directory"
              echo "Depth: $depth"
              echo "Expected Line: $expected_line"
              echo "-----------------------------------"


              # Check the first line of the file
              first_line=$(head -n 1 "$file")
              if [[ "$first_line" != "$expected_line" ]]; then
                echo "❌ Error: $file does not contain the required first line."
                echo "Expected: $expected_line"
                echo "Found: $first_line"
                exit 1
              fi
          done
          echo "✅ All markdown files contain the required first line."
