name: PR Title Formatter

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: Slashgear/action-check-pr-title@v4.3.0
        with:
          regexp: "^:( ft|docs)\/[a-z]+(-[a-z0-9]+)*$" # Regex the title should match.
          helpMessage: "Example: 'Add: ft/feature-name' or 'Update: docs/new-doc-about-visa-process'"
